import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers as ReaduxProvider } from "@/redux/providers";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/AuthContext";
import { TaskProvider } from "@/context/TaskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReaduxProvider>
        <AuthProvider>
          <TaskProvider>
              <body className={inter.className}>
                <NavBar />
                <main className="container mx-auto px-5 mt-4">{children}</main>
                <ToastContainer
                  position="top-center"
                  autoClose={1000}
                  theme="dark"
                />
              </body>
          </TaskProvider>
        </AuthProvider>
      </ReaduxProvider>
    </html>
  );
}
